name = "agita-clube"
pages_build_output_dir = "./public"
compatibility_date = "2026-01-01"

[[d1_databases]]
binding = "DB"
database_name = "agita-db"
database_id = "COLE_AQUI_O_ID_QUE_O_WRANGLER_MOSTRAR"
